const GUIAS_GAME8 = {
  "Pyro": {
    "amber": "https://game8.co/games/Genshin-Impact/archives/297535",
    "arlecchino": "https://game8.co/games/Genshin-Impact/archives/382103",
    "bennett": "https://game8.co/games/Genshin-Impact/archives/297522",
    "chevreuse": "https://game8.co/games/Genshin-Impact/archives/426201",
    "dehya": "https://game8.co/games/Genshin-Impact/archives/383716",
    "diluc": "https://game8.co/games/Genshin-Impact/archives/297518",
    "durin": "https://game8.co/games/Genshin-Impact/archives/462478",
    "gaming": "https://game8.co/games/Genshin-Impact/archives/437446",
    "hu_tao": "https://game8.co/games/Genshin-Impact/archives/314347",
    "klee": "https://game8.co/games/Genshin-Impact/archives/297521",
    "lyney": "https://game8.co/games/Genshin-Impact/archives/345540",
    "mavuika": "https://game8.co/games/Genshin-Impact/archives/461999",
    "nicole": "https://game8.co/games/Genshin-Impact/archives/406932",
    "thoma": "https://game8.co/games/Genshin-Impact/archives/337141",
    "xiangling": "https://game8.co/games/Genshin-Impact/archives/297530",
    "xinyan": "https://game8.co/games/Genshin-Impact/archives/305873",
    "yanfei": "https://game8.co/games/Genshin-Impact/archives/328765",
    "yoimiya": "https://game8.co/games/Genshin-Impact/archives/333497"
  },
  "Hydro": {
    "aino": "https://game8.co/games/Genshin-Impact/archives/537903",
    "ayato": "https://game8.co/games/Genshin-Impact/archives/345514",
    "barbara": "https://game8.co/games/Genshin-Impact/archives/297517",
    "candace": "https://game8.co/games/Genshin-Impact/archives/386384",
    "columbina": "https://game8.co/games/Genshin-Impact/archives/382106",
    "dahlia": "https://game8.co/games/Genshin-Impact/archives/516026",
    "furina": "https://game8.co/games/Genshin-Impact/archives/417212",
    "kokomi": "https://game8.co/games/Genshin-Impact/archives/337140",
    "mona": "https://game8.co/games/Genshin-Impact/archives/297526",
    "mualani": "https://game8.co/games/Genshin-Impact/archives/461994",
    "neuvillette": "https://game8.co/games/Genshin-Impact/archives/393054",
    "nilou": "https://game8.co/games/Genshin-Impact/archives/383715",
    "sigewinne": "https://game8.co/games/Genshin-Impact/archives/352956",
    "tartaglia": "https://game8.co/games/Genshin-Impact/archives/305862",
    "xingqiu": "https://game8.co/games/Genshin-Impact/archives/297531",
    "yelan": "https://game8.co/games/Genshin-Impact/archives/372781"
  },
  "Geo": {
    "albedo": "https://game8.co/games/Genshin-Impact/archives/312182",
    "chiori": "https://game8.co/games/Genshin-Impact/archives/382793",
    "gorou": "https://game8.co/games/Genshin-Impact/archives/336726",
    "illuga": "https://game8.co/games/Genshin-Impact/archives/555902",
    "kachina": "https://game8.co/games/Genshin-Impact/archives/462004",
    "linnea": "https://game8.co/games/Genshin-Impact/archives/551088",
    "navia": "https://game8.co/games/Genshin-Impact/archives/417194",
    "ningguang": "https://game8.co/games/Genshin-Impact/archives/297529",
    "noelle": "https://game8.co/games/Genshin-Impact/archives/297523",
    "xilonen": "https://game8.co/games/Genshin-Impact/archives/461997",
    "yunjin": "https://game8.co/games/Genshin-Impact/archives/314345",
    "zhongli": "https://game8.co/games/Genshin-Impact/archives/305858",
    "zibai": "https://game8.co/games/Genshin-Impact/archives/570263",
	"itto": "https://game8.co/games/Genshin-Impact/archives/345461"
  },
  "Electro": {
    "beidou": "https://game8.co/games/Genshin-Impact/archives/297528",
    "clorinde": "https://game8.co/games/Genshin-Impact/archives/417218",
    "cyno": "https://game8.co/games/Genshin-Impact/archives/315233",
    "dori": "https://game8.co/games/Genshin-Impact/archives/380569",
    "fischl": "https://game8.co/games/Genshin-Impact/archives/297524",
    "flins": "https://game8.co/games/Genshin-Impact/archives/538451",
    "iansan": "https://game8.co/games/Genshin-Impact/archives/345881",
    "ineffa": "https://game8.co/games/Genshin-Impact/archives/531360",
    "keqing": "https://game8.co/games/Genshin-Impact/archives/297534",
    "lisa": "https://game8.co/games/Genshin-Impact/archives/297515",
    "ororon": "https://game8.co/games/Genshin-Impact/archives/461993",
    "razor": "https://game8.co/games/Genshin-Impact/archives/297519",
    "sethos": "https://game8.co/games/Genshin-Impact/archives/451024",
    "varesa": "https://game8.co/games/Genshin-Impact/archives/500244",
    "yae_miko": "https://game8.co/games/Genshin-Impact/archives/327533",
	"alyosha": "https://game8.co/games/Genshin-Impact/archives/606884",
	"kuki_shinobu": "https://game8.co/games/Genshin-Impact/archives/346199",
	"kujou_sara": "https://game8.co/games/Genshin-Impact/archives/336727",
	"raiden": "https://game8.co/games/Genshin-Impact/archives/337161"

  },
  "Dendro": {
    "alhaitham": "https://game8.co/games/Genshin-Impact/archives/383712",
    "baizhu": "https://game8.co/games/Genshin-Impact/archives/314348",
    "collei": "https://game8.co/games/Genshin-Impact/archives/382079",
    "emilie": "https://game8.co/games/Genshin-Impact/archives/422493",
    "kaveh": "https://game8.co/games/Genshin-Impact/archives/386489",
    "kinich": "https://game8.co/games/Genshin-Impact/archives/461991",
    "kirara": "https://game8.co/games/Genshin-Impact/archives/409556",
    "lauma": "https://game8.co/games/Genshin-Impact/archives/538066",
    "nahida": "https://game8.co/games/Genshin-Impact/archives/383713",
    "nefer": "https://game8.co/games/Genshin-Impact/archives/538448",
    "tighnari": "https://game8.co/games/Genshin-Impact/archives/382082",
    "yaoyao": "https://game8.co/games/Genshin-Impact/archives/314174"
  },
  "Cryo": {
    "aloy": "https://game8.co/games/Genshin-Impact/archives/337957",
    "ayaka": "https://game8.co/games/Genshin-Impact/archives/315215",
    "charlotte": "https://game8.co/games/Genshin-Impact/archives/412428",
    "chongyun": "https://game8.co/games/Genshin-Impact/archives/297532",
    "citlali": "https://game8.co/games/Genshin-Impact/archives/461989",
    "diona": "https://game8.co/games/Genshin-Impact/archives/305872",
    "escoffier": "https://game8.co/games/Genshin-Impact/archives/385307",
    "eula": "https://game8.co/games/Genshin-Impact/archives/328764",
    "freminet": "https://game8.co/games/Genshin-Impact/archives/417207",
    "ganyu": "https://game8.co/games/Genshin-Impact/archives/312173",
    "kaeya": "https://game8.co/games/Genshin-Impact/archives/297516",
    "layla": "https://game8.co/games/Genshin-Impact/archives/386486",
    "lohen": "https://game8.co/games/Genshin-Impact/archives/580697",
    "mika": "https://game8.co/games/Genshin-Impact/archives/390096",
    "odette": "https://game8.co/games/Genshin-Impact/archives/606893",
    "qiqi": "https://game8.co/games/Genshin-Impact/archives/297533",
    "rosaria": "https://game8.co/games/Genshin-Impact/archives/314177",
    "sandrone": "https://game8.co/games/Genshin-Impact/archives/382107",
    "shenhe": "https://game8.co/games/Genshin-Impact/archives/346620",
    "skirk": "https://game8.co/games/Genshin-Impact/archives/333140",
    "wriothesley": "https://game8.co/games/Genshin-Impact/archives/417191"
  },
  "Anemo": {
    "chasca": "https://game8.co/games/Genshin-Impact/archives/462001",
    "faruzan": "https://game8.co/games/Genshin-Impact/archives/391897",
    "heizou": "https://game8.co/games/Genshin-Impact/archives/345516",
    "ifa": "https://game8.co/games/Genshin-Impact/archives/472693",
    "jahoda": "https://game8.co/games/Genshin-Impact/archives/538446",
    "jean": "https://game8.co/games/Genshin-Impact/archives/297536",
    "kazuha": "https://game8.co/games/Genshin-Impact/archives/332826",
    "lan_yan": "https://game8.co/games/Genshin-Impact/archives/486709",
    "lynette": "https://game8.co/games/Genshin-Impact/archives/345879",
    "prune": "https://game8.co/games/Genshin-Impact/archives/590328",
    "sayu": "https://game8.co/games/Genshin-Impact/archives/333496",
    "sucrose": "https://game8.co/games/Genshin-Impact/archives/297525",
    "varka": "https://game8.co/games/Genshin-Impact/archives/314346",
    "venti": "https://game8.co/games/Genshin-Impact/archives/297520",
    "xianyun": "https://game8.co/games/Genshin-Impact/archives/437445",
    "xiao": "https://game8.co/games/Genshin-Impact/archives/297527",
	"andarilho": "https://game8.co/games/Genshin-Impact/archives/309656",
	"mizuki": "https://game8.co/games/Genshin-Impact/archives/492414"
  },
  "Todos": {
	"aether": "https://game8.co/games/Genshin-Impact/archives/613906",
	"lumine": "https://game8.co/games/Genshin-Impact/archives/613906"
  }
};




